version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: sh -c 'cd ./src && gunicorn online_store.wsgi:application --bind 0.0.0.0:8000'
    volumes:
      - static_volume:/app/src/static
      - media_volume:/app/src/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    restart: always
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    restart: always
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always
volumes:
  postgres_data:
  static_volume:
  media_volume:
